------------------------TP 3 LES VUES--------------------------


--Question 1

CREATE VIEW V_EMP AS
SELECT
    E.EMPNUM,
    E.EMPNAME,
    E.DEPTNUM,
    E.EMPSAL + E.EMPCOMMISSION AS GAINS,
    D.LOC
FROM 
    EMPLOYER E
JOIN
    DEPARTEMENT D
ON
    E.DEPTNUM = D.DEPTNUM ;


--Question 2 

SELECT * FROM V_EMP
WHERE GAINS>2500 ;

--Question 3

UPDATE V_EMP
SET EMPNAME = 'MARTINN'
WHERE EMPNAME = 'MARTIN';

--Question 4

UPDATE V_EMP
SET LOC = 'SFAX'
WHERE EMPNAME = 'MARTINN';

--Question 5

CREATE VIEW V_EMP_10 AS
SELECT *
FROM
    EMPLOYER
WHERE
    DEPTNUM = 10 ;

--Question 5.1

INSERT INTO 
V_EMP_10 (EMPNUM, EMPNAME, EMPJOB, REQDATE, EMPSAL, EMPCOMMISSION, DEPTNUM, EMPMGR)
VALUES (1224, 'SALAH', 'ANALYST', TO_DATE('01/01/2022', 'DD/MM/YYYY'), 1500, NULL, 20, 7839);



