
-- Étape 1: Création de la table «DEPARTEMENT»


CREATE TABLE DEPARTEMENT(
    DEPTNUM NUMBER(4),
    DEPTNAME CHAR(20) CHECK (DEPTNAME = UPPER(DEPTNAME) AND DEPTNAME IN ('ACCOUNTING', 'RESEARCH', 'SALES', 'OPERATIONS')),
    LOC VARCHAR(20),
    CONSTRAINT PK_DEPTNUM PRIMARY KEY(DEPTNUM)
);


ALTER TABLE DEPARTEMENT
    MODIFY LOC VARCHAR(20) UNIQUE ;



-- Étape 2: Création de la table «EMPLOYE»


CREATE TABLE EMPLOYER (
    EMPNUM NUMBER(4) PRIMARY KEY,
    EMPNAME CHAR(15),
    EMPJOB VARCHAR(15) NOT NULL,
    REQDATE DATE NOT NULL,
    EMPSAL NUMBER(6,2) NOT NULL,
    EMPCOMM NUMBER(6,2),
    
);

ALTER TABLE EMPLOYER
    ADD DEPTNUM NUMBER(4);

ALTER TABLE EMPLOYER
    ADD CONSTRAINT FK_DEPNUM FOREIGN KEY (DEPTNUM) REFERENCES DEPARTEMENT(DEPTNUM);

ALTER TABLE EMPLOYER
    ADD EMPMGR NUMBER(4);

ALTER TABLE EMPLOYER
    ADD CONSTRAINT FK_EMPMGR FOREIGN KEY (EMPMGR) REFERENCES EMPLOYER(EMPNUM);

    



-- Question C : 

ALTER TABLE EMPLOYER
    ADD CONSTRAINT CHECK_EMPSAL CHECK (EMPSAL <= 800);


-- Question D :

ALTER TABLE EMPLOYER
    DROP CONSTRAINT CHECK_EMPSAL ;


-- Qestion E  :

ALTER TABLE EMPLOYER
    RENAME COLUMN EMPCOMM TO EMPCOMMISSION;


-- Question F  :

ALTER TABLE EMPLOYER
    ADD LNAME CHAR(20);

-- Question G  :

ALTER TABLE EMPLOYER
    MODIFY LNAME CHAR(40);

-- Question H :

ALTER TABLE EMPLOYER
    DROP COLUMN LNAME ;


-- Étape 3: Création de la table

CREATE TABLE GRADE_SAL(
    SALGRADE NUMBER(2),
    SALLOW NUMBER(4),
    SALHIGH NUMBER (4)
);

ALTER TABLE GRADE_SAL
   ADD CONSTRAINT PK_SALGRADE PRIMARY KEY (SALGRADE);