CREATE TABLE DEPARTEMENT(
    DEPTNUM NUMBER(4) ,
    DEPTNAME CHAR(20),
    LOC VARCHAR(20),
    CONSTRAINT PK_DEPTNUM PRIMARY KEY(DEPTNUM),
    CONSTRAINT UPPER_DEPTNAME CHECK (DEPTNAME = UPPER(DEPTNAME)),
    CONSTRAINT DEPTS_DEPTNAME CHECK (DEPTNAME IN ('ACCOUNTING','RESEARCH','SALES','OPERATIONS'))

);

ALTER TABLE DEPARTEMENT
    ADD CONSTRAINT UNIQUE_LOC UNIQUE (LOC);


CREATE TABLE EMPLOYER (
    EMPNUM NUMBER(4) PRIMARY KEY,
    EMPNAME CHAR(15),
    EMPJOB VARCHAR(15) NOT NULL,
    REQDATE DATE NOT NULL,
    EMPSAL NUMBER(6,2),
    EMPCOMM NUMBER(6,2),
    DEPTNUM NUMBER(4),
    EMPMGR NUMBER(4),
    CONSTRAINT FK_EMPMGR FOREIGN KEY (EMPMGR) REFERENCES EMPLOYER(EMPNUM),
    CONSTRAINT FK_DEPNUM FOREIGN KEY (DEPTNUM) REFERENCES DEPARTEMENT(DEPTNUM)
);


-- Question C : 

ALTER TABLE EMPLOYER
    ADD CONSTRAINT CHECK_EMPSAL CHECK (EMPSAL <= 800);


-- Question D :

ALTER TABLE EMPLOYER
    DROP CONSTRAINT CHECK_EMPSAL ;
